There was an exception thrown in Fleet:

<%= @message %>

<%= @exception.message %>

<%= @exception.backtrace.join("\n") %>
